# Site settings
name: Eloi Navarro
title: Eloi Navarro | Android Engineer
description: A different kind of android engineer focused on building practical and useful experiences
url: https://eloinavarro.github.io/
baseurl: ''
email: web@eloinavarro.com
cover: https://eloinavarro.github.io/img/og.png
logo: https://eloinavarro.github.io/img/emojis/technologist.png
resume: https://eloinavarro.github.io/resume.pdf
social:
  - title: email
    url: mailto:web@eloinavarro.com
  - title: github
    url: https://github.com/EloiNavarro
  - title: linkedin
    url: https://www.linkedin.com/in/eloinavarro

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
